apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: f0mzebol3-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/f0mzebol3-dotnet-basic-gitops